In [17]:
# ESERCIZO M4-D6

In [18]:
# ESRCIZIO 1
"""Abbiamo una lista di liste. 
# Che tipo di struttura dati o matematica potrebbe rappresentare? 
Notate che tutte le liste "interne" sono della stessa dimensione.
# Come facciamo per accedere ad un elemento in particolare? """

mat = [[0,1,2,3,4],
      [5,6,7,8,9],
      [10,11,12,13,14]]
#La variabile mat rappresenta una matrice

""" Per accedere a un elemento specifico in questa matrice, 
bisogna indicare l'indice della riga e l'indice della colonna come ad Esempio:"""

mat[1][0]
# in questo caso  ho richiamato il valore 10 che si trova nella lista alla posizione "0" della pozione numro "1"

5

In [19]:
# ESERCIZIO 2
""" Trasformiamo la lista dell'esercizio precedente in un array NumPy:
mat = np.array(mat
# Come facciamo per accedere ai singoli elementi? """

# Trasformiamo la lista in un array NumPy

import numpy as np
mat = np.array([
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14]
])

# Si può accedere all'elemento nella seconda riga e terza colonna in questo modo:
elemento = mat[1, 2]
print(elemento)

7


In [20]:
# ESERCIZIO 3
"""Abbiamo il seguente array NumPy:
linear_data = np.array([x for x in range(27)])
Lo ridimensioniamo mediante il metodo .reshape():
reshaped_data = linear_data.reshape((3, 3, 3))
# Quante dimensioni ha il nuovo array?
# Come facciamo per accedere ai singoli elementi? """

# Abbiamo il seguente array NumPy.
import numpy as np
linear_data = np.array([x for x in range(27)])
# Lo ridimensioniamo tramite il metodo .reshape().
reshaped_data = linear_data.reshape(3,3,3)
#Quante dimensioni ha il nuovo array?
print(linear_data)
print(reshaped_data.shape)
#Come facciamo per accedere ai singoli elementi?
print(reshaped_data)
#Nome variabile e parentesi quadre con virgole per indicare le posizioni dell'elemento che si vuole richiamare
reshaped_data[1,0,2]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
(3, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


11

In [21]:
# ESERCIZIO 4: 1/3 - 2/3
"""Abbiamo un territorio cittadino diviso in quattro quadranti; in ognuno di essi c'è 
uno store: UL UR
           LL LR
Vogliamo contare quanti clienti vengono serviti dai diversi store: creiamo una 
struttura dati adeguata con un array NumPy, dove il conteggio di ogni store 
parta da zero."""

""" Creiamo un ciclo di 100 iterazioni che riempia, a caso, uno dei quattro 
quadranti, simulando quindi diversi clienti serviti dai vari store.
# Alla fine, che valore ha lo store UR? E lo store LL?
# Quali store hanno avuto più di 25 clienti?
# Quanti clienti hanno avuto di preciso questi store?
# Qual è la loro somma? """

import numpy as np
import random
quadranti = np.array(["UL","UR","LL","RR"])
clienti = np.array([0,0,0,0])
for x in range(100):
    pos = random.randint(0,3)
    clienti[pos] += 1
for el in range(len(clienti)):
    print(str(quadranti[el]) + " : " +str(clienti[el]))
#Alla fine, che valore ha lo store UR? E lo store LL?
print("\nLo store " + str(quadranti[1]) + " ha " + str(clienti[1]) +
       " clienti e lo store " + str(quadranti[2]) + " ha " + str(clienti[2])+ " clienti.")

#Quale store ja più di 25 clienti? Quanti clienti hanno avuto di preciso questi store?
print("Store con più di 25 clienti:")
somma = 0
for el in range(len(quadranti)): 
    if clienti[el] > 25 :
        print(str(quadranti[el]) +  " ha " + str(clienti[el]) + " clienti.")
        somma += clienti[el]
print("La somma dei clienti è: " + str(somma))    


UL : 26
UR : 30
LL : 25
RR : 19

Lo store UR ha 30 clienti e lo store LL ha 25 clienti.
Store con più di 25 clienti:
UL ha 26 clienti.
UR ha 30 clienti.
La somma dei clienti è: 56


In [22]:
# ESERCIZIO 5: 3/3
""" Ripetiamo la traccia precedente, ma stavolta abbiamo nove quadranti e 200 
iterazioni: UL UC UR
            ML MC MR
            LL LC LR
L'anno prossimo ci aspettiamo 4 volte tanto i valori appena ottenuti; simuliamo 
velocemente il tutto e stampiamo il risultato. """


# Ripetiamo la traccia precedente ma stavolta abbiamo nove quadranti e 200 iterazioni.
import numpy as np
import random
quadranti = np.array(["UL","UC","UR","ML","MC","MR","LL","LC","LR"])
clienti = np.array([0,0,0,0,0,0,0,0,0])
for x in range(200):
    pos = random.randint(0,8)
    clienti[pos] += 1
print("\nPer questo anno la situazione è la seguente:")
for el in range(len(clienti)):
    print(str(quadranti[el]) + " : " +str(clienti[el]))
# L'anno prossimo ci aspettiamo 4 volte i valori appena ottenuti; simuliamo velocemente il tutto e stampiamo il risultato
for el in range(len(clienti)):
    clienti[el] *=4
print("\nPer il prossimo anno la situazione attesa è la seguente:")
for el in range(len(clienti)):
    print(str(quadranti[el]) + " : " +str(clienti[el]))


Per questo anno la situazione è la seguente:
UL : 18
UC : 23
UR : 22
ML : 17
MC : 22
MR : 31
LL : 22
LC : 20
LR : 25

Per il prossimo anno la situazione attesa è la seguente:
UL : 72
UC : 92
UR : 88
ML : 68
MC : 88
MR : 124
LL : 88
LC : 80
LR : 100


In [ ]:
# ESERCIZIO 6
"""Chiediamo all'utente di inserire un numero, dividiamolo per 5 e poi stampiamo 
il risultato a video.
Gestiamo correttamente le eccezioni nel caso l'utente immetta un input errato."""

while True:                                                                                                                 
    print("Inserisci il numero da dividere per 5:")
    try:    
        num = int(input())
    except:print("Hai inserito un valore non valido: riprova.")
    else :
        print(num/5)
        break


In [2]:
# ESERCIZIO 7
""" In una catena di montaggio abbiamo una struttura metallica di 28.75 cm di 
lunghezza; per assicurarne la stabilità, è necessario inserire 15 rivetti, dei quali 
uno all'inizio e uno alla fine, e tutti quanti separati dalla stessa distanza; come 
possiamo calcolare i punti esatti in cui inserire i rivetti tramite NumPy? """

import numpy as np
lung_strutt = 28.75
num_rivetti = 15
punti_esatti = np.linspace(0,lung_strutt,num=num_rivetti)
print("I punti in cui posizionare i rivetti sono: " , punti_esatti)

I punti in cui posizionare i rivetti sono:  [ 0.          2.05357143  4.10714286  6.16071429  8.21428571 10.26785714
 12.32142857 14.375      16.42857143 18.48214286 20.53571429 22.58928571
 24.64285714 26.69642857 28.75      ]


In [23]:
# ESERCIZIO 8
""" Scarichiamo l'Iris dataset da qui: https://archive.ics.uci.edu/dataset/53/iris
Troveremo un file .data, che è un CSV, e un file .names con i metadati; questa 
versione del dataset non ha i nomi di colonna.
• Leggiamo il file e carichiamolo in un DataFrame mediante pd.read_csv()
senza utilizzare altri parametri
• Stampiamo le prime cinque righe 
• Stampiamo i nomi di colonna: sono corretti? """

import pandas as pd
df=pd.read_csv(r"C:/Users/VITA MARIA/Desktop/iris.csv")
# Stampiamo le prime 5 righe
print(df.head())

# Stampiamo i nomi delle colonne: sono corretti?
df.columns #Ovviamente no

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [4]:
#  ESERCIZIO 9
""" Dal dataset di prima:
• Leggiamo il file e carichiamolo in un DataFrame, aggiungendo i nomi di 
colonna — che si trovano nel file .names — come parametro di 
pd.read_csv()
• Stampiamo le prime cinque righe e le ultime dieci
• Stampiamo un riepilogo dei descrittori statistici del dataset"""


df=pd.read_csv(r"C:/Users/VITA MARIA/Desktop/iris.csv",header=None,names=['sepal length in cm','sepal width in cm',
                                                                          'petal length in cm',
                                                                          'petal width in cm','class'])

#Stampiamo le prime cinque righe
df.head()

# E le ultime 10
df.tail(10)

# Stampiamo un riepilogo dei descrittori statistici del dataset
df.describe()

sepal length in cm sepal width in cm petal length in cm  \
count                 151               151                151   
unique                 36                24                 44   
top                     5                 3                1.5   
freq                   10                26                 13   

       petal width in cm   class  
count                151     151  
unique                23       4  
top                   .2  Setosa  
freq                  29      50

In [7]:
# ESERCIZIO 10
""" Andiamo a questo link e scarichiamo una serie di dataset: 
https://www.kaggle.com/datasets/ahmettezcantekin/beginner-datasets
Tra i vari dataset presenti, ce n'è uno che contiene diverse qualità di vini e le 
misure di diverse proprietà organolettiche, wine.csv;
Leggiamo quindi il dataset wine.csv, e visualizziamone le prime e le ultime 
righe;
Leggiamo nuovamente il dataset, ma stavolta considerando soltanto le ultime 6 
colonne, ricordandoci che in totale il dataset ha 13 colonne;
Visualizziamo un resoconto dei descrittori statistici di questa versione."""

import pandas as pd
wine = pd.read_csv("C:/Users/VITA MARIA/Desktop/wine.csv")
wine

# Leggiamo nuovamente il dataset ma stavolta considerando solo le ultime 6 colonne ricordandoci 
# che in totale il dataset ha 13 colonne
wine = pd.read_csv("C:/Users/VITA MARIA/Desktop/wine.csv",usecols=[x for x in range(7,13,1)])
wine

# Visualizziamo un resoconto dei descrittori statistici di questa versione
wine.describe()

density           pH    sulphates      alcohol      quality
count  6497.000000  6497.000000  6497.000000  6497.000000  6497.000000
mean      0.994697     3.218501     0.531268    10.491801     5.818378
std       0.002999     0.160787     0.148806     1.192712     0.873255
min       0.987110     2.720000     0.220000     8.000000     3.000000
25%       0.992340     3.110000     0.430000     9.500000     5.000000
50%       0.994890     3.210000     0.510000    10.300000     6.000000
75%       0.996990     3.320000     0.600000    11.300000     6.000000
max       1.038980     4.010000     2.000000    14.900000     9.000000

In [8]:
# ESERCIZIO 11. Abbiamo la seguente matrice. Creiamo un ndarray con gli stessi valori
import numpy as np
arr_matrix = np.matrix([(1,1,1,1),
                        (5,1,1,1),
                        (20,-4,0,42)])
arr_ = np.array([el for el in arr_matrix])
arr_ = np.ndarray.reshape(arr_,(1,12))
arr_

array([[ 1,  1,  1,  1,  5,  1,  1,  1, 20, -4,  0, 42]])